<a href="https://colab.research.google.com/github/young-tryler/ThucHanhDeepLearning/blob/main/2001230980_BuiQuocTri_B1_THDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2001230980 - Bùi Quốc Trí - Lab1_DeepLearning

In [10]:
# TÀI LIỆU LAB 1 PANDAS
import numpy as np

# --- 3.1. Tạo array 1-chiều ---
# Cách 1
my_list = [1, 9, 15, 39]
my_numpy_array = np.array(my_list)
print('Numpy array (Cách 1):', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39])
print('Numpy array (Cách 2):', a)
print('Shape của a:', a.shape) # Xem kích thước
print('Dtype của a:', a.dtype) # Xem kiểu dữ liệu

# --- 3.2. Array 2-chiều ---
c = np.array([(1, 2, 3), (4, 5, 6)])
print('\nArray 2-chiều c:\n', c)
print('Shape của c:', c.shape)
print('Dtype của c:', c.dtype)

# --- 3.3. Array 3-chiều ---
d = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print('\nArray 3-chiều d:\n', d)
print('Shape của d:', d.shape)

# --- 3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1 ---
e_zeros = np.zeros((2, 2))
f_ones = np.ones((3, 3))
print('\nZero matrix:\n', e_zeros)
print('One matrix:\n', f_ones)

# --- 3.5. Reshape và Flatten ma trận ---
# 3.5.1. Reshape thay đổi kích thước
e_matrix = np.array([[1., 2., 3.], [4., 5., 6.]])
f_reshaped = e_matrix.reshape(3, 2)
print('\nMa trận sau khi reshape (3, 2):\n', f_reshaped)

g_3d = np.array([[[1., 2., 3.], [4., 5., 6.]],
                 [[7., 8., 9.], [10., 11., 12.]]])
h_34 = g_3d.reshape(3, 4)
j_322 = g_3d.reshape(3, 2, 2)
k_232 = g_3d.reshape(2, 3, 2)
print('Reshape (3, 4):\n', h_34)
print('Reshape (3, 2, 2):\n', j_322)

# 3.5.2. Flatten chuyển array nhiều chiều về 1 chiều
f_flat = e_matrix.flatten()
j_flat = g_3d.flatten()
print('\nFlatten e_matrix:', f_flat)
print('Flatten g_3d:', j_flat)

# --- 3.6. Thêm dòng dữ liệu với hstack và vstack ---
f_stack = np.array([1., 2., 3.])
g_stack = np.array([4., 5., 6.])
h_stack = np.hstack((f_stack, g_stack)) # Chiều ngang
v_stack = np.vstack((f_stack, g_stack)) # Chiều dọc
print('\nHorizontal Append (hstack):', h_stack)
print('Vertical Append (vstack):\n', v_stack)

# --- 3.7. Sinh mảng số ngẫu nhiên ---
# 3.7.1. Số nguyên ngẫu nhiên
rand_1d = np.random.randint(100, size=(5,))
rand_2d = np.random.randint(100, size=(3, 4))
rand_3d = np.random.randint(100, size=(3, 4, 3))
print('\nRandom 1-D array số nguyên:', rand_1d)

# 3.7.2. Số thực ngẫu nhiên [0, 1]
rand_f_1d = np.random.rand(5)
rand_f_2d = np.random.rand(3, 4)
print('Random 1-D array số thực:', rand_f_1d)

# 3.7.3. Phân phối chuẩn Gaussian
rand_normal = np.random.normal(5, 0.5, 10) # Tạo đồ thị hình chuông (5: giá trị trọng tâm, 0.5: độ rời rạc, 10, số lượng phần tư )
print('Random Gaussian:\n', rand_normal)

# 3.7.4. Lấy ngẫu nhiên từ mảng cho trước
choice_val = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
choice_matrix = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print('Lấy 1 giá trị ngẫu nhiên:', choice_val)

# --- 3.8. Thay đổi giá trị của ma trận (Sử dụng np.asarray) ---
A = np.matrix(np.ones((5, 5)))
np.asarray(A)[2] = 2 # Thay đổi toàn bộ dòng số 3 thành giá trị 2
print('\nMa trận A sau thay đổi dòng 3:\n', A)

# --- 3.9. Sinh dãy số theo khoảng cho trước ---
a_range = np.arange(1, 20)
b_range = np.arange(1, 20, 2) # Bước nhảy bằng 2
a_linspace = np.linspace(1., 5., num=10) # Chia đều 10 phần tử
print('\nArange (bước nhảy 2):', b_range)
print('Linspace (1 đến 5, 10 số):', a_linspace)

# --- 3.10. Index và slice ---
slice_arr = np.array([(1, 2, 3), (4, 5, 6)])
print('\nDòng đầu tiên:', slice_arr[0])
print('Cột thứ hai:', slice_arr[:, 1])
print('Phần tử tại dòng 1, cột 2 (0-indexed):', slice_arr[1, 2])

Numpy array (Cách 1): [ 1  9 15 39]
Numpy array (Cách 2): [ 1  9 15 39]
Shape của a: (4,)
Dtype của a: int64

Array 2-chiều c:
 [[1 2 3]
 [4 5 6]]
Shape của c: (2, 3)
Dtype của c: int64

Array 3-chiều d:
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Shape của d: (2, 2, 3)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Ma trận sau khi reshape (3, 2):
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
Reshape (3, 4):
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Reshape (3, 2, 2):
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]

Flatten e_matrix: [1. 2. 3. 4. 5. 6.]
Flatten g_3d: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]

Horizontal Append (hstack): [1. 2. 3. 4. 5. 6.]
Vertical Append (vstack):
 [[1. 2. 3.]
 [4. 5. 6.]]

Random 1-D array số nguyên: [57 86 29 13 42]
Random 1-D array số thực: [0.57219273 0.24672761 0.45971526 0.41580535 0.69672413]
Random Gaussian:
 [5.27871592 4.58359892 4.65203557 

In [ ]:
# TÀI LIỆU LAB 1 PANDAS
import pandas as pd
import numpy as np

# --- 6. TÌM HIỂU ĐỐI TƯỢNG SERIES ---
# Tạo Series từ list
s1 = pd.Series([1., 2., 3.])
print('Pandas Series s1:\n', s1)

# Tạo Series có gán nhãn Index cụ thể
s2 = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print('First value của s2 với index "a":', s2['a'])

# Tạo Series từ Dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
my_series_dict = pd.Series(calories)
print('Series từ Dictionary:\n', my_series_dict)

# --- 7. TẠO ĐỐI TƯỢNG DATAFRAME ---
# Chuyển từ Numpy --> Pandas DataFrame
h_arr = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h_arr)
print('\nDataFrame chuyển từ Numpy:\n', df_h)

# Chuyển ngược từ Pandas --> Numpy Array
numpy_back = np.array(df_h)

# Tạo DataFrame từ Dictionary có đặt tên cột
dic_data = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic_data)
print('\nDataFrame từ Dictionary:\n', df_dic)

# Tạo DataFrame từ mảng ngẫu nhiên (20 x 4) và gán tên cột
r_data = np.random.randn(20, 4)
df_rand = pd.DataFrame(r_data, columns=['so1', 'so2', 'so3', 'so4'])
print('\n5 Dòng đầu tiên của df_rand (head):\n', df_rand.head())

# --- 7.1. Thao tác nâng cao trên DataFrame (Trích xuất từ hình ảnh minh họa) ---
# Lọc (Filtering), Cắt lát (Slicing) và Xóa (Drop)
print('\n--- Thao tác nâng cao trên DataFrame ---')
# Cắt lấy đoạn dòng từ index 1 đến 3
print('Cắt dòng từ 1 đến 3:\n', df_rand[1:4])

# Lọc dữ liệu theo điều kiện: lấy các dòng mà giá trị cột 'so1' >= 0
print('Lọc dòng có so1 >= 0:\n', df_rand[df_rand['so1'] >= 0])

# Xóa cột dữ liệu (Drop columns)
df_dropped = df_rand.drop(columns=['so3', 'so4'])
print('DataFrame sau khi xóa cột so3 và so4:\n', df_dropped.head())

# --- Nối nhiều DataFrame (Concat), Loại bỏ trùng lặp & Sắp xếp ---
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'], 'Age': [25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [28, 30]}, index=[3, 4])

# Nối 2 DataFrame lại với nhau (Ngang/Dọc)
df_concat = pd.concat([df1, df2])
print('\nKết quả nối nối 2 DataFrame:\n', df_concat)

# Loại bỏ trùng lặp (Drop duplicates) dựa trên tên
df_no_dup = df_concat.drop_duplicates(subset=['Name'])
print('Sau khi xóa dữ liệu trùng tên:\n', df_no_dup)

# Sắp xếp (Sort) dữ liệu theo cột tăng dần
df_sorted = df_concat.sort_values(by='Age')
print('Sắp xếp tăng dần theo tuổi:\n', df_sorted)

# Đổi tên cột (Rename)
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('DataFrame sau khi đổi tên cột:\n', df_rename)

# --- 7.2 & 7.3. Đọc dữ liệu CSV và Gom nhóm (Groupby) ---
# Cấu trúc mẫu đọc file CSV từ tài liệu[cite: 490]:
# df_csv = pd.read_csv('đường_dẫn_file.csv', skipinitialspace=True, index_col=False) [cite: 493]

# Demo giả lập tính năng Groupby tính toán thống kê dựa trên dữ liệu df_concat [cite: 493]
print('\n--- Thống kê gom nhóm (Groupby) theo Tên ---')
print(df_concat.groupby('Name').mean()) # Tính trung bình tuổi theo từng nhóm tên [cite: 493]

In [ ]:
# TÀI LIỆU LAB 2 - CƠ BẢN TENSORFLOW

import tensorflow as tf

# ==========================================
# 1. KHỞI TẠO TENSOR & ĐỊNH DẠNG (RANK)
# ==========================================
# Rank 0 (Scalar)
rank_0_tensor = tf.constant(4)
print("Rank 0:", rank_0_tensor)

# Rank 1 (Vector)
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print("Rank 1:", rank_1_tensor)

# Rank 2 (Matrix)
rank_2_tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32)
print("Rank 2:\n", rank_2_tensor)

# Xem thuộc tính Tensor
print("Kích thước (Shape):", rank_2_tensor.shape)
print("Kiểu dữ liệu (Dtype):", rank_2_tensor.dtype)

# ==========================================
# 2. CÁC HÀM TẠO TENSOR TỰ ĐỘNG
# ==========================================
tensor_zeros = tf.zeros([3, 3])
tensor_ones = tf.ones([2, 3])
tensor_fill = tf.fill([2, 2], 9)
tensor_linspace = tf.linspace(5.0, 20.0, 5)
tensor_range = tf.range(3.0, 7.0, delta=0.5)

# Sinh số ngẫu nhiên
tensor_normal = tf.random.normal([3, 3], mean=0.0, stddev=1.0)
tensor_uniform = tf.random.uniform([5], minval=10, maxval=20)
tensor_shuffled = tf.random.shuffle(tensor_uniform)

# Ép kiểu dữ liệu (Casting)
tensor_cast = tf.cast(rank_0_tensor, dtype=tf.float32)

# ==========================================
# 3. CÁC PHÉP TOÁN TOÁN HỌC & LOGIC
# ==========================================
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Toán học cơ bản
c_add = tf.add(a, b)
c_sub = tf.subtract(a, b)
c_mul = tf.multiply(a, b) # Nhân từng phần tử (Element-wise)
c_div = tf.divide(a, b)
mat_mul = tf.matmul(a, b) # Nhân ma trận toán học

# Phép toán logic & Câu lệnh điều kiện (tf.where)
x = tf.constant([1, 2, 3, 4, 5])
y = tf.constant([5, 4, 3, 2, 1])
condition = tf.less(x, y) # Trả về Tensor Boolean [True, True, False, False, False]
result_where = tf.where(condition, x + y, x - y)

# ==========================================
# 4. BIẾN ĐỔI HÌNH DẠNG TENSOR (RESHAPE, CONCAT, TRANSPOSE)
# ==========================================
tensor_to_reshape = tf.constant([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tf.reshape(tensor_to_reshape, [3, 2])
transposed_tensor = tf.transpose(tensor_to_reshape)

# Nối Tensor (Concatenate và Stack)
t1 = tf.constant([[1, 2], [3, 4]])
t2 = tf.constant([[5, 6], [7, 8]])
concat_axis0 = tf.concat([t1, t2], axis=0) # Nối theo dòng
concat_axis1 = tf.concat([t1, t2], axis=1) # Nối theo cột

# Cắt ảnh / Tensor ngẫu nhiên (Ví dụ giả lập dữ liệu ảnh 3 chiều)
mock_image = tf.random.normal([10, 10, 3])
cropped_image = tf.image.random_crop(mock_image, size=[5, 5, 3])

# ==========================================
# 5. ĐỒ THỊ TÍNH TOÁN (GRAPH MODE)
# ==========================================
@tf.function
def graph_calculation(val1, val2):
    add_val = tf.add(val1, val2)
    return tf.multiply(add_val, 2)

print("\nChạy thử hàm trong Graph Mode:", graph_calculation(tf.constant(5), tf.constant(10)).numpy())

# ==========================================
# 6. XÂY DỰNG MODEL MÔ PHỎNG (LỚP ĐỐI TƯỢNG)
# ==========================================
# Định nghĩa cấu trúc tầng Dense thủ công kế thừa từ tf.Module
class SimpleDense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        # Khởi tạo ma trận trọng số Weights và Bias ngẫu nhiên bằng tf.Variable
        self.w = tf.Variable(tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')

    def __call__(self, x):
        # Công thức tuyến tính: y = xW + b
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y) # Hàm kích hoạt ReLU

# Khởi tạo mô hình giả định đầu vào 3 tính năng, đầu ra 2 tính năng
my_dense_layer = SimpleDense(in_features=3, out_features=2)

# Chạy thử mô hình với một Tensor đầu vào mẫu
input_data = tf.constant([[2.0, 1.0, 3.0]])
output_data = my_dense_layer(input_data)

print("\n--- KẾT QUẢ KIỂM TRA MÔ HÌNH DENSE LAYER ---")
print("Đầu ra sau khi qua lớp Dense & kích hoạt ReLU:\n", output_data.numpy())