<a href="https://colab.research.google.com/github/tui-ten-tri/ThucHanhDeepLearning/blob/main/lab1_th_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
my_list = [[1.,2., 3.],[4., 5., 6.]]
my_list2 = [[1.,2., 3.]]
my_list3 = [[1.,2., 3.]]
# print(my_list)
np_arr = np.array(my_list)
np_arr2 = np.array(my_list2)
np_arr3 = np.array(my_list3)

# print(np_arr)

# print(np_arr.shape)
# print(np_arr.reshape(3,2))
# print(np_arr.dtype)

# print(np.ones(shape=(2,2)))

# print(np_arr.flatten())

# print(np.hstack((np_arr3, np_arr2)))
# print(np.vstack((np_arr3, np_arr2)))




[[1. 2. 3. 1. 2. 3.]]
[[1. 2. 3.]
 [1. 2. 3.]]
