<a href="https://colab.research.google.com/github/young-tryler/ThucHanhDeepLearning/blob/main/lab1_th_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2001230980 - Bùi Quốc Trí - Lab1_DeepLearning
import numpy as np

# =========================================
# 1. TẠO LIST PYTHON
# =========================================

my_list = [[1., 2., 3.], [4., 5., 6.]]
my_list2 = [[1., 2., 3.]]
my_list3 = [[1., 2., 3.]]

print("Python List:")
print(my_list)

# =========================================
# 2. CHUYỂN SANG NUMPY ARRAY
# =========================================

np_arr = np.array(my_list)
np_arr2 = np.array(my_list2)
np_arr3 = np.array(my_list3)

print("\nNumPy Array:")
print(np_arr)

# =========================================
# 3. SHAPE
# =========================================

print("\nShape:")
print(np_arr.shape)

# =========================================
# 4. RESHAPE
# =========================================

print("\nReshape 2x3 -> 3x2:")
print(np_arr.reshape(3, 2))

# =========================================
# 5. DTYPE
# =========================================

print("\nDtype:")
print(np_arr.dtype)

# =========================================
# 6. ONES
# =========================================

print("\nnp.ones((2,2)):")
print(np.ones(shape=(2, 2)))

# =========================================
# 7. FLATTEN
# =========================================

print("\nFlatten:")
print(np_arr.flatten())

# =========================================
# 8. HSTACK
# =========================================

print("\nHorizontal Stack:")
print(np.hstack((np_arr3, np_arr2)))

# =========================================
# 9. VSTACK
# =========================================

print("\nVertical Stack:")
print(np.vstack((np_arr3, np_arr2)))

# =========================================
# 10. RANDOM RAND
# =========================================

print("\nRandom Rand (3,2,3):")
print(np.random.rand(3, 2, 3))

# =========================================
# 11. RANDOM NORMAL
# =========================================

print("\nRandom Normal:")
print(np.random.normal(5, 1, 10))

# =========================================
# 12. RANDOM CHOICE
# =========================================

print("\nRandom Choice:")
print(np.random.choice([1, 2, 3], size=(5, 5)))

# =========================================
# 13. MATRIX
# =========================================

A = np.matrix(np.ones((5, 5)))

print("\nMatrix A:")
print(A)

# Chuyển sang array để chỉnh sửa
B = np.array(A)

# Sửa hàng thứ 2
B[2] = 2

print("\nModified Array B:")
print(B)

# =========================================
# 14. ARANGE
# =========================================

print("\nArange:")
print(np.arange(1, 20, 3))

# =========================================
# 15. LINSPACE
# =========================================

print("\nLinspace:")
print(np.linspace(1., 5., num=20))

# =========================================
# 16. TRUY CẬP PHẦN TỬ
# =========================================

print("\nFirst Row:")
print(np_arr[0])

print("\nFirst Column:")
print(np_arr[:, 0])

Python List:
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

NumPy Array:
[[1. 2. 3.]
 [4. 5. 6.]]

Shape:
(2, 3)

Reshape 2x3 -> 3x2:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

Dtype:
float64

np.ones((2,2)):
[[1. 1.]
 [1. 1.]]

Flatten:
[1. 2. 3. 4. 5. 6.]

Horizontal Stack:
[[1. 2. 3. 1. 2. 3.]]

Vertical Stack:
[[1. 2. 3.]
 [1. 2. 3.]]

Random Rand (3,2,3):
[[[0.25403965 0.88544748 0.51162799]
  [0.30694476 0.83955236 0.53630542]]

 [[0.29035181 0.76782491 0.34022472]
  [0.78897093 0.25095493 0.11765058]]

 [[0.76539854 0.71218217 0.0398853 ]
  [0.50408627 0.63002013 0.83672151]]]

Random Normal:
[4.51859585 4.85486696 4.53328285 4.40613705 5.0640091  4.21351728
 3.76475476 4.59042398 5.89108378 6.77510331]

Random Choice:
[[2 3 3 1 3]
 [2 1 1 2 2]
 [3 2 1 1 2]
 [2 1 3 1 1]
 [1 2 2 2 3]]

Matrix A:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Modified Array B:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Arange:
[ 

In [ ]:
import numpy as np
import pandas as pd

# =========================================
# 1. SERIES
# =========================================

a = pd.Series([1, 2, 3], index=['a', 'b', 'c'])

print("Series a:")
print(a)

# Truy cập phần tử
print("\nAccess a['a']:")
print(a['a'])

# =========================================
# 2. SERIES TỪ DICTIONARY
# =========================================

week = {
    "t2": "thuhai",
    "t3": "thuba"
}

b = pd.Series(week)

print("\nSeries từ Dictionary:")
print(b)

# =========================================
# 3. DATAFRAME TỪ NUMPY ARRAY
# =========================================

c = np.array([
    [1, 2],
    [3, 4]
])

df_c = pd.DataFrame(c)

print("\nDataFrame từ NumPy Array:")
print(df_c)

# Chuyển DataFrame -> NumPy Array
print("\nDataFrame -> NumPy Array:")
print(np.array(df_c))

# =========================================
# 4. DATAFRAME TỪ DICTIONARY
# =========================================

dic = {
    'name': ['nguyen van a', 'nguyen van b'],
    'age': [10, 20]
}

print("\nDictionary:")
print(dic)

df_dic = pd.DataFrame(dic)

print("\nDataFrame từ Dictionary:")
print(df_dic)

# =========================================
# 5. RANDOM DATAFRAME
# =========================================

# randn:
# random số thực theo phân phối chuẩn

d = np.random.randn(20, 2)

df_d = pd.DataFrame(
    d,
    columns=['so1', 'so2']
)

print("\nRandom DataFrame:")
print(df_d)

# =========================================
# 6. THÔNG TIN DATAFRAME
# =========================================

print("\nShape:")
print(df_d.shape)

print("\nColumns:")
print(df_d.columns)

print("\nDtypes:")
print(df_d.dtypes)

# =========================================
# 7. TRUY CẬP CỘT
# =========================================

print("\nColumn so1:")
print(df_d['so1'])

# =========================================
# 8. TRUY CẬP NHIỀU CỘT
# =========================================

print("\nColumns so1 và so2:")
print(df_d[['so1', 'so2']])

# =========================================
# 9. LẤY DÒNG ĐẦU
# =========================================

print("\nFirst 5 rows:")
print(df_d.head())

# =========================================
# 10. THỐNG KÊ CƠ BẢN
# =========================================

print("\nDescribe:")
print(df_d.describe())

Series a:
a    1
b    2
c    3
dtype: int64

Access a['a']:
1

Series từ Dictionary:
t2    thuhai
t3     thuba
dtype: object

DataFrame từ NumPy Array:
   0  1
0  1  2
1  3  4

DataFrame -> NumPy Array:
[[1 2]
 [3 4]]

Dictionary:
{'name': ['nguyen van a', 'nguyen van b'], 'age': [10, 20]}

DataFrame từ Dictionary:
           name  age
0  nguyen van a   10
1  nguyen van b   20

Random DataFrame:
         so1       so2
0   1.919692 -0.734504
1  -0.443749 -0.824022
2   0.478901 -0.605081
3   0.842482  1.354113
4   0.709410 -0.774196
5  -0.939561  1.888152
6  -1.202966 -0.529169
7  -1.246064  0.354929
8  -1.133825 -1.361067
9   0.770894  0.987537
10 -1.311991 -0.363233
11 -0.146000  0.447866
12  0.164843 -0.424446
13  0.355577  0.276465
14  0.555057 -2.047460
15 -0.597483 -1.985665
16 -1.102258  1.789414
17  1.810902 -0.344908
18  0.759723 -2.368394
19  1.170581  0.227681

Shape:
(20, 2)

Columns:
Index(['so1', 'so2'], dtype='object')

Dtypes:
so1    float64
so2    float64
dtype: object



In [ ]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4);
print(rank_0_tensor);

print(tf.constant(9, tf.int16))
print(tf.constant(1.12, tf.float32))

print(tf.constant([1.0, 2.3, 3.4]))

print(tf.constant([[1, 2],[3, 4],[5, 6]], tf.int16))

print(tf.constant(np.random.randint(2,4), dtype=tf.int64))

print(tf.fill(3, 10))

print(tf.fill([3,3], 9))

print(tf.linspace(5, 20, 5))

print(tf.range(3, 7, delta=0.7))

print(tf.random.normal([5]));

print(tf.random.normal([3,3]))

print(tf.random.truncated_normal([5]))

print(tf.random.truncated_normal([3,2,4]))

print(tf.random.uniform([3, 2], minval=10, maxval=20))

df_e = tf.random.uniform([5], minval=1, maxval=20)

print(df_e)

print(tf.random.shuffle(df_e))

print(tf.cast(df_e, dtype=tf.int32))

print(tf.sqrt(df_e))

print(df_e + tf.sqrt(df_e))

print(tf.add(df_e,tf.sqrt(df_e)))

print(df_e * tf.sqrt(df_e))

print(tf.multiply(df_e,tf.sqrt(df_e)))

print(tf.subtract(df_e,tf.sqrt(df_e)))

print(tf.divide(df_e,tf.sqrt(df_e)))

print(tf.scalar_mul(3, df_e))

print(tf.math.reciprocal(df_e))

print(tf.math.mod(df_e, tf.sqrt(df_e)))

print(tf.negative)

print(tf.round(df_e))
print(tf.math.rint(df_e))
print(tf.math.ceil(df_e))
print(tf.math.floor(df_e))














tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor([1.  2.3 3.4], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int16)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)
tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float64)
tf.Tensor([3.  3.7 4.4 5.1 5.8 6.5], shape=(6,), dtype=float32)
tf.Tensor([ 0.44214132  0.7752509  -0.28580904 -0.79537797 -0.6718898 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 1.5194567  -0.07994737 -0.45843184]
 [-1.6754875   0.21375448 -1.2641456 ]
 [ 1.4291468  -0.33955398  0.29660273]], shape=(3, 3), dtype=float32)
tf.Tensor([-0.3106914   0.6329551  -0.6594254   0.61043984 -1.189638  ], shape=(5,), dtype=float32)
tf.Tensor(
[[[-1.2791712  -0.5801042   1.3677508   0.77162397]
  [-1.902373   -1.853052   -0.4280216   0.10369797]]

 [[ 0.48567015